### ISSUE TITLE
RFE: please provide update for `httpcore` 0.17

### ISSUE THREAD

**Issue by kloczek** [romis2012/httpx-socks#14]
https://github.com/romis2012/httpx-socks/blob/271b5f2d11b12ab16841a7402536a1f6e0c41af2/requirements.txt#L2
https://github.com/romis2012/httpx-socks/blob/271b5f2d11b12ab16841a7402536a1f6e0c41af2/setup.py#L39-L42

**Comment by romis2012** [comment]
The latest version of httpx (0.23.3) depends on httpcore<0.17.0,>=0.15.0, so we have the same dependencies

**Comment by kloczek** [comment]
FYI: in unreleased commit that requirement has been changed https://github.com/encode/httpx/commit/46a5d38bd73caa31827c7da15e4fa30ad60b925f and looks like except formal requrement none of actual code changes was necessary to add.

**Comment by romis2012** [comment]
> ...unreleased commit...

So we are waiting for the release

**Comment by kloczek** [comment]
So in mean time you may add simillar commit 😋 
Looks like none `httpcore` 0.17 changes makes adds API changes ..

**Comment by romis2012** [comment]
It makes absolutely no sense right now

**Comment by kloczek** [comment]
> So we are waiting for the release

And it happened .. 😋

**Comment by romis2012** [comment]
Updated in v0.7.6
