### ISSUE TITLE
[Feature request] support socks5h in environment variable

### ISSUE THREAD

**Issue by PaTTeeL** [romis2012/httpx-socks#15]
Could httpx-socks be possible to support the `export https_proxy=socks5h://ip:port` which forces curl to resolve DNS remotely in same environment ? 

Maybe convert 'socks5h' to 'socks5' for python-socks, which avoids breaking backward compatibility ?

**Comment by romis2012** [comment]
No, it could not. See https://github.com/romis2012/python-socks/pull/8, https://github.com/romis2012/httpx-socks/issues/8, ...

**Comment by romis2012** [comment]
It will take you a couple of lines of code to read the value of the environment variable and replace "socks5h" with "socks5". This is not the "httpx-socks"/"python-socks" responsibility

**Comment by PaTTeeL** [comment]
> It will take you a couple of lines of code to read the value of the environment variable and replace "socks5h" with "socks5". This is not the "httpx-socks"/"python-socks" responsibility

Got it.
Maybe I should read environment variable and translate them into socks5 request with different argument like 'rdns' ?

**Comment by romis2012** [comment]
> Got it.
Maybe I should read environment variable and translate them into socks5 request with different argument like 'rdns' ?

Yes, something like that
