### ISSUE TITLE
ModuleNotFoundError: No module named 'httpcore.backends'

### ISSUE THREAD

**Issue by plotski** [romis2012/httpx-socks#16]
The reason seems to be that httpcore now exports some selected stuff from `httpcore._backends` instead of exporting `httpcore.backends` and it was done without bumping the major version number.

https://github.com/encode/httpcore/pull/699/commits/833b5eb425116e0f5aea6151bf2c3c8789330331  
https://www.encode.io/httpcore/network-backends/

**Comment by romis2012** [comment]
Fixed in v0.7.7

**Comment by plotski** [comment]
Thanks for the quick fix!
