### ISSUE TITLE
Update dependencies to add support for httpx 0.26

### ISSUE THREAD

**Issue by morian** [romis2012/httpx-socks#19]
Hi!

Could you upgrade the dependencies to bring support for httpx v0.26?
It already seems to work as expected when forced but due to the dependency hell, it prevents the use of pytest-httpx 0.29, which means using pytest 7 rather than pytest 8....

Thanks!

**Comment by romis2012** [comment]
Updated in v0.8.1

**Comment by morian** [comment]
Thanks for this quick fix, have a nice day!
