### ISSUE TITLE
The proxy will not automatically reconnect after disconnecting

### ISSUE THREAD

**Issue by GeekDuanLian** [romis2012/httpx-socks#5]
Steps to reproduce:
- Open the proxy, request a URL that will stay connected, such as `https://www.google.com/`
- Close and reopen the proxy, request the URL again.
- Raised an error: `httpcore.WriteError: [Errno 104] Connection reset by peer`

At present, you can only manually execute `self._transport.aclose()` to reset the connection status, and then requesting the URL again will not cause an error.

**Comment by romis2012** [comment]
Your scenario works fine for me

```python
async def test_case():
    transport = AsyncProxyTransport.from_url('http://user:password@127.0.0.1:7770')
    async with httpx.AsyncClient(transport=transport) as client:
        res = await client.get('https://check-host.net/ip')
        print(res.status_code)

        await asyncio.sleep(16)  # restart proxy server here

        res = await client.get('https://check-host.net/ip-info')
        print(res.status_code)

asyncio.run(test_case())
```

**Comment by GeekDuanLian** [comment]
It seems that the error only occurs when using http2.
I use the same code as you, except:
```diff
@@ -1,5 +1,5 @@
 async def test_case():
-    transport = AsyncProxyTransport.from_url('http://user:password@127.0.0.1:7770')
+    transport = AsyncProxyTransport.from_url('http://user:password@127.0.0.1:7770', http2=True)
     async with httpx.AsyncClient(transport=transport) as client:
         res = await client.get('https://check-host.net/ip')
         print(res.status_code)
```
Will cause problems.

**Comment by romis2012** [comment]
> It seems that the error only occurs when using http2.

You are using `http2` incorrectly, you should pass it to AsyncClient(...) too

> Will cause problems.

What problems does this cause?

**Comment by romis2012** [comment]
Ok. 

When using `http2=True` we get the error:  `httpcore.RemoteProtocolError: Server disconnected`

```python
url = 'https://check-host.net/ip'
proxy_url = 'http://user:password@127.0.0.1:7770'
http2 = True
transport = SyncProxyTransport.from_url(proxy_url, http2=http2)
with httpx.Client(transport=transport, http2=http2) as client:
    res = client.get(url)
    print(res.status_code)
    print(res.http_version)

    time.sleep(4)  # restart proxy server here

    res = client.get(url)
    print(res.status_code)
    print(res.http_version)
```

But if we are using builtin httpx proxy we get the same error.

```python
url = 'https://check-host.net/ip'
proxy_url = 'http://user:password@127.0.0.1:7770'
http2 = True
with httpx.Client(proxies=proxy_url, http2=http2) as client:
    res = client.get(url)
    print(res.status_code)
    print(res.http_version)

    # timeout should be less than SyncHTTPProxy._keepalive_expiry
    time.sleep(4)  # restart proxy server here

    res = client.get(url)
    print(res.status_code)
    print(res.http_version)
```

In short,  the problem is how `httpx/httpcore` manages its connection pool. So it's `httpx/httpcore` issue. You should create new issue [here](https://github.com/encode/httpx/issues)

**Comment by GeekDuanLian** [comment]
Yes, I filed an issue on httpx, thanks for your reply.
