### ISSUE TITLE
Using different timeout configuration for proxy and request?

### ISSUE THREAD

**Issue by synchronizing** [romis2012/httpx-socks#6]
I didn't see this documented within `httpx-socks`, and so I'm wondering: is there any way to set individual timeout configuration for both (a) the initial proxy connection, and (b) the intended request? Thank you!

**Comment by romis2012** [comment]
You should use the standard `httpx` approach (https://www.python-httpx.org/advanced/#fine-tuning-the-configuration)

```python
transport = ...
timeout = httpx.Timeout(...)
async with httpx.AsyncClient(transport=transport, timeout=timeout) as client:
    response = await client.get(url)
```

**Comment by synchronizing** [comment]
Awesome, thank you. Wasn't sure if the `httpx.Timeout` was integrated to work with `httpx-socks`.
