### ISSUE TITLE
Type hints

### ISSUE THREAD

**Issue by sometato** [romis2012/httpx-socks#7]
Hi,

This looks like an awesome companion to httpx. I see some type hints in here. Would it be possible to add a `py.typed` file and maybe some more type hints?

Here's some information on that: https://mypy.readthedocs.io/en/stable/installed_packages.html?highlight=py.typed#creating-pep-561-compatible-packages

I like to use `mypy` to test my typed repositories as well.

Thank you for your time.

**Comment by romis2012** [comment]
We don't aim to completely cover the code with type annotations. Moreover, we don't use any type checkers (like mypy). So there is no sense in the `py.typed` file.

**Comment by sometato** [comment]
I understand. `py.typed` files signal `mypy` to check for type hints in the package if used as a library. Even if all aren't type hinted, I think some might work and the rest are `ANY`s. That said, I think it's good to validate the type hints to keep from breaking that, so probably best to use `mypy` if you have a `py.typed`. I can understand not wanting to go down that route.

Thank you!
