### ISSUE TITLE
DNS resolving through SOCKS

### ISSUE THREAD

**Issue by vvch** [romis2012/httpx-socks#8]
What about resolving DNS requests through SOCKS proxy? Like socks5h:// in original `requests` package? Do this package support such possibility or is it planned to add this in the future?

**Comment by romis2012** [comment]
This is the default behavior for socks5 proxies. If you want to change it, use `rdns` argument of the ProxyTransport ctor e.g. `transport = SyncProxyTransport.from_url(..., rdns=False)`
